### ISSUE TITLE
Bar Chart Displaying Wrong Y Values JUST rightAxis，but leftAxis is OK!!!

### ISSUE THREAD

**Issue by AbnerPei** [ChartsOrg/Charts#5189]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/jjatie/Charts/blob/master/CONTRIBUTING.md).

> I found the same issue: [#4896](https://github.com/ChartsOrg/Charts/issues/4896)

## What did you do?
```
            /// It's OK
            let yAxis = barChartView.leftAxis
            yAxis.axisMinimum = 0
            yAxis.axisMaximum = 5
            yAxis.granularity = 1
            yAxis.labelCount = 6
            yAxis.forceLabelsEnabled = true
```
<img width="303" alt="image" src="https://github.com/user-attachments/assets/10a3afbb-8348-4ef7-b640-245936cd9197">

```
            /// It's wrong
            let yAxis = barChartView.rightAxis
            yAxis.axisMinimum = 0
            yAxis.axisMaximum = 5
            yAxis.granularity = 1
            yAxis.labelCount = 6
            yAxis.forceLabelsEnabled = true
```
<img width="309" alt="image" src="https://github.com/user-attachments/assets/ea211657-38b7-4e73-be17-3b61023234a0">

## What did you expect to happen?

I expect leftAxis or rightAxis has the same。

## What happened instead?

ℹ Please replace this with of what happened instead.  

## DGCharts Environment

**DGCharts version/Branch/Commit Number:**
**Xcode version:** 15.3
**Swift version:** 5.10
**Platform(s) running DGCharts:** 5.1.0
**macOS version running Xcode:** Sonoma 14.3.1

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by AbnerPei** [comment]
## You do this, you can do it again，as shown below
<img width="1158" alt="image" src="https://github.com/user-attachments/assets/7da261b2-2a71-4814-9935-26aec2217529">

**Comment by Viktor-by** [comment]
Hi @AbnerPei ,

Please try setting `axisDependency` of your data set to `.right`. By default, the chart is plotted against the left axis.

Another workaround is to configure left and right axis with the same parameters (`axisMinimum`, `axisMaximum` etc.), then disable the left axis.

**Comment by AbnerPei** [comment]
> Hi @AbnerPei ,
> 
> Please try setting `axisDependency` of your data set to `.right`. By default, the chart is plotted against the left axis.
> 
> Another workaround is to configure left and right axis with the same parameters (`axisMinimum`, `axisMaximum` etc.), then disable the left axis.

Thank you for your reply. It was very helpful. I just set `axisDependency` to `.right`!!!
